import { question as q } from "../assessmentSchema.js";

export const aiProductEngineerQuestions = Object.freeze([
  q("ai-01", "craft", "A new model looks better in demos but has not been evaluated on production tasks. What should happen before rollout?", "Run a versioned representative eval set with agreed quality thresholds and regression checks.", "Ship it to all users and compare support tickets after a week.", "Ask the model vendor whether the new version is generally more capable.", "Choose whichever model produces the most persuasive single demo."),
  q("ai-02", "craft", "Users report that a retrieval assistant confidently misses policy details. What is the strongest first diagnostic step?", "Evaluate retrieval recall and ranking on labeled queries before changing generation prompts.", "Increase the generation temperature so the answer explores more possibilities.", "Add a longer system prompt instructing the model to be more accurate.", "Replace every document chunk with a much larger chunk."),
  q("ai-03", "craft", "An agent summarizes uploaded documents and can also call internal tools. How should prompt-injection risk be bounded?", "Treat document text as untrusted, isolate instructions, and allowlist tool actions server-side.", "Tell the model once that uploaded documents may contain malicious instructions.", "Remove all punctuation from uploaded documents before sending them to the model.", "Let the model decide whether a document instruction appears trustworthy."),
  q("ai-04", "craft", "A support agent needs to read accounts and occasionally issue credits. Which permission design is strongest?", "Use scoped credentials and require explicit approval for irreversible credit actions.", "Give the agent one administrator token so every tool call is consistent.", "Expose only a free-form SQL tool and rely on the prompt for restrictions.", "Permit every action but add a note telling the agent to be cautious."),
  q("ai-05", "craft", "Downstream code requires a stable object from a model call. What is the most reliable implementation?", "Use schema-constrained output, validate it server-side, and retry or fail explicitly.", "Parse the model response with a regular expression that expects one example format.", "Ask for JSON in natural language and assume compliant models always return it.", "Store the raw prose response and let each downstream consumer interpret it."),
  q("ai-06", "craft", "A workflow drafts high-impact compliance decisions. Where should human review be placed?", "Before consequential action, with evidence, uncertainty, and an editable recommendation.", "Only after the action when a customer challenges the result.", "At random for a fixed one percent of all decisions regardless of risk.", "Nowhere, provided the system prompt says to follow regulations."),
  q("ai-07", "systems", "A multi-step AI job can outlive an HTTP request and individual steps may retry. What architecture fits best?", "Persist a state machine in a durable queue with idempotent step execution.", "Keep the request open until every model and tool call returns.", "Run all steps in the browser and store progress only in local storage.", "Retry the complete workflow recursively whenever any step fails."),
  q("ai-08", "systems", "The primary model provider is unavailable during a customer workflow. What is the best fallback behavior?", "Enter an explicit tested degraded mode with clear limits and deterministic recovery.", "Silently switch to any available model without checking behavior differences.", "Return fabricated placeholder output so the workflow can appear complete.", "Retry continuously with no deadline until the provider recovers."),
  q("ai-09", "systems", "A production answer must be explainable during an incident without storing unnecessary personal data. What should traces contain?", "Versioned prompt, model, retrieval and tool events with identifiers and redacted payloads.", "Only the final answer because intermediate steps create too much noise.", "Every raw customer payload forever so no context is ever missing.", "A screenshot of the interface taken after each completed request."),
  q("ai-10", "systems", "Model latency and cost are rising as usage grows. Which response is most sustainable?", "Set budgets, measure by task, cache safe work, and route requests by required capability.", "Use the cheapest model for every request regardless of quality requirements.", "Remove observability so logging no longer contributes to request cost.", "Shorten every prompt by the same percentage without evaluating quality."),
  q("ai-11", "judgment", "A provider announces a major model-version upgrade with limited backward compatibility. How should it be introduced?", "Shadow and canary it against versioned evals, monitor regressions, and retain rollback.", "Change the model alias immediately because the provider recommends upgrading.", "Wait until the old version is disabled and then test in production.", "Run one internal prompt and roll out if its wording looks improved."),
  q("ai-12", "judgment", "A team wants to send complete customer records to improve answer quality. What is the best privacy tradeoff?", "Minimize and redact inputs, prove which fields improve quality, and enforce retention limits.", "Send all fields because model providers are responsible for downstream privacy.", "Hash the customer name but keep every other sensitive field unchanged.", "Accept lower privacy whenever a stakeholder predicts quality will improve."),
  q("ai-13", "judgment", "When should an AI agent be allowed to act without an approval step?", "When actions are low-risk, reversible, tightly scoped, monitored, and bounded by policy.", "Whenever the model reports confidence above fifty percent.", "After the agent has completed ten successful actions in a test environment.", "For any action requested by an authenticated user, including irreversible ones."),
  q("ai-14", "judgment", "A prototype performs well for a small internal group. What evidence best supports a production-readiness decision?", "Representative evals, security boundaries, failure handling, observability, and a rollback plan.", "A polished interface and enthusiastic comments from the prototype team.", "The absence of exceptions during a single uninterrupted demonstration.", "A written promise from the model provider about general reliability."),
  q("ai-15", "delivery", "Inference jobs arrive faster than workers can complete them. What should the system do?", "Apply bounded admission, queue limits, retry budgets, and visible backpressure.", "Accept every job into memory so no customer receives a rejection.", "Add immediate retries to each queued job until one worker is free.", "Increase request timeouts and leave queue growth unmonitored."),
  q("ai-16", "delivery", "An agent has executed an incorrect external action in production. What is the first incident response?", "Disable the risky capability, preserve traces, contain impact, and start a clear incident process.", "Delete the traces so sensitive details cannot be seen by responders.", "Tune the prompt in production while allowing the same actions to continue.", "Wait for a second occurrence to confirm the incident is reproducible."),
  q("ai-17", "delivery", "A stakeholder asks why the assistant cannot guarantee a correct answer every time. What is the clearest response?", "Explain measured performance, known failure modes, safeguards, and where human judgment remains.", "Say that modern language models are too complex for useful explanation.", "Promise a guarantee after adding more instructions to the system prompt.", "Avoid discussing uncertainty because it may reduce stakeholder confidence."),
  q("ai-18", "delivery", "A six-week AI product engagement has several unknowns. How should delivery be sequenced?", "Build a thin end-to-end slice around the highest-risk assumption, evaluate it, then expand.", "Complete the full interface before testing retrieval, model, or tool behavior.", "Implement every planned feature in parallel and integrate during the final week.", "Begin with the easiest low-risk features so visible output accumulates quickly.")
]);
