import { question as q } from "../assessmentSchema.js";

export const brandSystemsDesignerQuestions = Object.freeze([
  q("bd-01", "craft", "A new brand must feel distinctive across product, editorial, and sales contexts. What should guide the visual system first?", "A clear strategic idea translated into recognizable principles that can govern varied executions.", "A collection of current visual trends selected for maximum immediate novelty.", "One highly detailed logo treatment that remains identical in every context.", "The personal style of whichever designer starts the first campaign."),
  q("bd-02", "craft", "A type system feels premium in headlines but fails in dense product interfaces. What is the strongest solution?", "Define complementary display and utility roles with tested hierarchy, metrics, and fallbacks.", "Use the display face at every size so brand consistency is never diluted.", "Reduce interface line height until the display face fits the existing components.", "Convert all product copy to images so typography remains exact."),
  q("bd-03", "craft", "A signature palette has poor contrast in functional states. How should the color system evolve?", "Keep expressive brand colors while adding accessible functional roles and tested pairings.", "Lower text opacity so low-contrast combinations feel more subtle.", "Use the signature color for every status because repetition builds recognition.", "Remove semantic status distinctions and rely on surrounding copy."),
  q("bd-04", "craft", "A detailed logo becomes unreadable in favicons and small interface marks. What is the correct response?", "Create a responsive mark family with simplified small-size forms and clear usage thresholds.", "Shrink the master logo unchanged so every detail remains conceptually present.", "Add a glow around the logo whenever it appears below thirty pixels.", "Use a different unrelated symbol at small sizes without documenting the relationship."),
  q("bd-05", "craft", "A campaign needs imagery that feels owned rather than like generic premium stock. What art-direction approach is strongest?", "Define subject, framing, light, material, color behavior, and rejection criteria tied to the brand idea.", "Search only for images tagged luxury and choose the darkest options.", "Apply one color filter to unrelated images after they are selected.", "Let each channel owner choose images independently for speed."),
  q("bd-06", "craft", "A composition system must support expressive editorial pages and practical product screens. What should the grid provide?", "Stable alignment logic with flexible spans, rhythm, and intentional exceptions.", "One fixed poster layout that every screen must reproduce exactly.", "No alignment rules, because expressiveness requires complete freedom.", "A set of decorative shapes placed wherever empty space appears."),
  q("bd-07", "systems", "Teams keep recreating campaign assets with inconsistent crops and treatments. What system addresses this?", "Create reusable templates, asset variants, naming, metadata, and governed source files.", "Ask teams to copy the latest exported image from the public website.", "Store all source and final assets in one unstructured shared folder.", "Approve every individual crop manually without defining reusable rules."),
  q("bd-08", "systems", "A motion identity is being added across web, video, and product. What makes it systematic?", "Define motion principles, timing families, transitions, accessibility behavior, and channel examples.", "Use the same long logo animation before every interaction.", "Choose random easing curves so motion never feels repetitive.", "Animate only decorative backgrounds and leave state changes unexplained."),
  q("bd-09", "systems", "The brand layout collapses when a headline wraps differently on small screens. What should responsive behavior define?", "Set hierarchy, reflow, crop, simplification, and type rules for each meaningful constraint.", "Scale the complete desktop composition down as one fixed canvas.", "Force headlines onto one line by reducing font size without a lower limit.", "Hide any text that does not fit the original desktop shape."),
  q("bd-10", "systems", "A distinctive brand treatment conflicts with readable text and interface focus. What is the correct system decision?", "Keep expression in appropriate layers while enforcing accessible contrast, hierarchy, and control states.", "Prioritize distinctiveness because accessibility can be addressed in a later campaign.", "Apply the treatment only to users who have not enabled dark mode.", "Reduce all body copy to short labels so contrast matters less."),
  q("bd-11", "judgment", "Regional teams need flexibility but the brand is becoming unrecognizable. How should governance respond?", "Separate non-negotiable recognition assets from adaptable components and document decision rights.", "Lock every asset globally and prohibit regional changes of any kind.", "Allow each region to redefine the logo, type, and palette independently.", "Create more approval meetings without clarifying which choices are flexible."),
  q("bd-12", "judgment", "A wordmark works in English but expands significantly in localized markets. What should be planned?", "Test scripts and expansion early, define lockup behavior, and collaborate with native language experts.", "Reduce localized type until every word occupies the English width.", "Use the English wordmark in every market regardless of comprehension.", "Let automated translation choose line breaks in final artwork."),
  q("bd-13", "judgment", "A successful identity needs to evolve without losing recognition. Which change strategy is strongest?", "Identify core memory structures, evolve weaker layers deliberately, and validate recognition across touchpoints.", "Replace every recognizable asset at once so the relaunch feels substantial.", "Never change any brand element after initial launch.", "Follow the newest competitor style while retaining the company name."),
  q("bd-14", "judgment", "Critique feedback asks for more visual impact but gives no reason. What should the designer do?", "Clarify the intended audience response and communication problem before proposing focused changes.", "Increase size, saturation, and motion across every element.", "Ignore the feedback because impact is purely subjective.", "Create several unrelated styles and ask stakeholders to vote without criteria."),
  q("bd-15", "delivery", "Multiple teams will implement a new visual system after handoff. What documentation is most useful?", "Principles, tokens, templates, examples, edge cases, source assets, and ownership guidance.", "A presentation of launch artwork without reusable files or specifications.", "A long list of forbidden uses with no examples of correct adaptation.", "One flattened PDF containing every asset at a single size."),
  q("bd-16", "delivery", "A campaign requires source files, web assets, social crops, and print output. How should delivery be structured?", "Use a named source hierarchy, export matrix, color profiles, versioning, and acceptance checklist.", "Export every file manually with whichever name the designer remembers.", "Send only the editable master and ask each recipient to make exports.", "Use one compressed image for all print and digital placements."),
  q("bd-17", "delivery", "A brand launch spans product, marketing, social, and partner channels. What QA approach is strongest?", "Audit a representative touchpoint matrix for identity, content, accessibility, and technical output.", "Review only the homepage because every other channel should copy it.", "Check that the logo appears somewhere and approve the remaining execution.", "Ask each channel team to self-certify with no shared criteria."),
  q("bd-18", "delivery", "Stakeholders disagree about whether the identity is ready to launch. How should alignment be reached?", "Return to agreed objectives and criteria, show evidence, name tradeoffs, and assign the decision owner.", "Continue producing options until everyone has the same personal preference.", "Choose the most senior person's favorite without recording the rationale.", "Delay the launch indefinitely because brand decisions require unanimous agreement.")
]);
