import { question as q } from "../assessmentSchema.js";

export const creativeFrontendDeveloperQuestions = Object.freeze([
  q("fe-01", "craft", "A highly art-directed page uses clickable div elements for every action. What is the best correction?", "Use native semantic controls and preserve the visual treatment with CSS.", "Keep the div elements and add cursor pointer to make intent clearer.", "Add a click handler to the page container and infer which item was clicked.", "Replace every action with an anchor element even when it does not navigate."),
  q("fe-02", "craft", "A gallery must align editorial text with irregular media while remaining robust as content changes. Which CSS approach is strongest?", "Use Grid with explicit tracks and intrinsic sizing constraints for the composition.", "Absolutely position every item from pixel coordinates taken from the design.", "Use JavaScript to calculate every element position after each resize event.", "Place the entire composition in one fixed-width image."),
  q("fe-03", "craft", "A cinematic hero crop works on desktop but hides the product on phones. What should responsive art direction do?", "Provide breakpoint-specific crops or sources that keep the product as the focal subject.", "Use the same source and reduce opacity so the missing product is less obvious.", "Disable the hero image on phones and leave only the background color.", "Stretch the desktop image vertically until the product enters the phone frame."),
  q("fe-04", "craft", "A display face overlaps adjacent copy after its webfont loads. What is the most reliable fix?", "Define stable metrics, suitable line height, fallback adjustments, and tested text containers.", "Hide overflow on every heading so overlap is no longer visible.", "Delay rendering the complete page for several seconds after load.", "Reduce letter spacing below zero until the heading becomes narrower."),
  q("fe-05", "craft", "A portfolio page looks sharp but its large imagery delays the first useful render. What is the best response?", "Serve correctly sized modern formats, prioritize the focal image, and lazy-load later media.", "Compress every image to the same tiny dimensions regardless of display size.", "Load all original images immediately so later scrolling is always instant.", "Replace meaningful product images with blurred decorative gradients."),
  q("fe-06", "craft", "Several entrance animations compete and cause layout movement. How should motion be choreographed?", "Establish hierarchy, animate transform and opacity, and keep layout dimensions stable.", "Increase every duration so viewers have time to follow all movement.", "Animate width and height on every element to make the page feel dynamic.", "Start all animations simultaneously with different random easing curves."),
  q("fe-07", "systems", "A server-rendered interactive canvas produces hydration mismatches. What boundary is most appropriate?", "Keep deterministic markup server-rendered and isolate browser-only state behind a client boundary.", "Read window dimensions during server rendering and assume they match the browser.", "Suppress every hydration warning without changing the component boundaries.", "Move all page content into one client component to remove server rendering."),
  q("fe-08", "systems", "A rich project detail route adds a large library that most visitors never use. What should happen?", "Split it at the route or interaction boundary and preload only when intent is likely.", "Bundle it into the main entry so dependency loading is predictable.", "Duplicate the library in each component that needs one function.", "Load the library from an unversioned public CDN on every page."),
  q("fe-09", "systems", "A WebGL scene is the primary visual but some devices cannot initialize it. What is the correct fallback?", "Show a deliberately composed static asset with equivalent subject and messaging.", "Leave a blank region because unsupported devices are outside the target audience.", "Retry context creation continuously until the device accepts it.", "Replace the complete page with a technical WebGL error message."),
  q("fe-10", "systems", "A visual interaction fails only in a subset of production browsers. What observability is most useful?", "Capture versioned release, browser capability, route, error, and bounded interaction context.", "Record full screen video for every visitor without notice.", "Log only the generic message that an interaction failed.", "Wait for users to identify the browser and exact source line themselves."),
  q("fe-11", "judgment", "A custom horizontal project rail works with a pointer but traps keyboard users. What is the best remedy?", "Provide logical focus order, keyboard controls, visible focus, and reachable exit behavior.", "Remove focus outlines so the trapped state is less visually distracting.", "Add a note that keyboard users should switch to a mouse.", "Make the complete rail one tab stop with no way to choose an item."),
  q("fe-12", "judgment", "A page relies on intense parallax and looping motion. How should reduced-motion preference be handled?", "Replace nonessential motion with stable states while preserving content and task completion.", "Slow every animation slightly but retain the same travel distance and loops.", "Disable the entire page because its concept depends on movement.", "Ignore the preference when motion is part of the approved visual direction."),
  q("fe-13", "judgment", "The exact design requires a fragile overlap that breaks with translated copy. What is the best fidelity decision?", "Preserve the visual intent with resilient constraints and document the small composition change.", "Hard-code the source-language dimensions and clip any translated text.", "Remove all expressive layout so every locale uses a generic template.", "Ship the fragile overlap and ask localization to shorten every translation."),
  q("fe-14", "judgment", "A form submission fails after several fields are completed. What error experience is strongest?", "Preserve values, show a focused summary, mark fields clearly, and support retry.", "Clear the form so the user can begin again with a clean state.", "Show only a red border around the submit button with no message.", "Display the raw provider exception and stack trace above the form."),
  q("fe-15", "delivery", "A one-off editorial component is likely to recur across several pages. How should it enter the design system?", "Extract stable tokens and behavior after validating real reuse, with examples and accessibility states.", "Immediately generalize every prop before a second use case exists.", "Copy the complete component into each page so teams can customize freely.", "Put only its colors in the design system and leave behavior undocumented."),
  q("fe-16", "delivery", "A release includes complex layout, video, and form behavior. What is the best cross-browser QA strategy?", "Test a risk-based browser and device matrix with real interactions and visual checkpoints.", "Open the homepage in the developer's primary browser and approve the release.", "Rely only on unit tests because browsers implement the same standards.", "Test every historical browser version equally regardless of audience data."),
  q("fe-17", "delivery", "A client asks for an estimate before animation and browser risks are explored. What is the most credible response?", "State assumptions, isolate a short technical spike, and estimate ranges around known risks.", "Give one precise date immediately to demonstrate senior confidence.", "Estimate only the number of components visible in the design file.", "Exclude QA and integration because they are not direct implementation work."),
  q("fe-18", "delivery", "A launch introduces a severe layout regression on mobile. What should the team do first?", "Contain or roll back the release, reproduce the viewport, add a regression check, then fix.", "Patch production CSS repeatedly without preserving a reproducible case.", "Wait for analytics to show whether enough users are affected.", "Disable mobile scrolling so users cannot reach the broken section.")
]);
