import { question as q } from "../assessmentSchema.js";

export const fullStackProductEngineerQuestions = Object.freeze([
  q("fs-01", "craft", "A client retries an order request after a timeout and duplicate orders appear. What is the correct API design?", "Require an idempotency key and atomically return the original result for repeated requests.", "Reject every request that arrives within one minute of another request.", "Generate a new order each time and merge duplicates in a nightly job.", "Increase the client timeout so retries become less likely."),
  q("fs-02", "craft", "Creating a record and reserving related inventory must succeed or fail together. What is the strongest boundary?", "Use one database transaction around the invariant and emit side effects after commit.", "Run both writes concurrently and retry whichever one reports an error.", "Write inventory first and assume the record creation will usually succeed.", "Store the intended changes in browser state until both APIs respond."),
  q("fs-03", "craft", "An authenticated user can change another account by modifying an ID in the URL. What is missing?", "Object-level authorization that checks the requested resource against the caller.", "A stronger password policy for every user in the application.", "Client-side validation that hides IDs belonging to other accounts.", "Encryption of the numeric ID before it is placed in the URL."),
  q("fs-04", "craft", "A query filters by tenant and status, then orders recent records, and has become slow. What should guide indexing?", "Use the query plan and add a selective composite index matching filter and order access.", "Add a separate index to every column in the table regardless of usage.", "Cache every database row in application memory indefinitely.", "Increase the database connection count until the query becomes faster."),
  q("fs-05", "craft", "A large table needs a new required column without a long production lock. What migration sequence is safest?", "Add it compatibly, backfill in batches, switch reads and writes, then enforce the constraint.", "Add the required column with a computed default in one blocking transaction at peak traffic.", "Stop all application traffic until every row is updated manually.", "Create a second table and abandon all historical records."),
  q("fs-06", "craft", "A payment provider posts webhooks to an internet-facing endpoint. What must be verified?", "Verify the raw-body signature, timestamp tolerance, event identity, and idempotent processing.", "Trust the event because the request uses HTTPS and contains a provider name.", "Accept the status in the browser return URL as authoritative.", "Allow only requests whose user agent string matches the provider documentation."),
  q("fs-07", "systems", "A background task may fail transiently after partially calling an external service. Which queue design is strongest?", "Use idempotent handlers, bounded retries with backoff, and a dead-letter path.", "Retry instantly forever so every task eventually succeeds.", "Acknowledge the job before work starts to prevent duplicate execution.", "Store jobs only in process memory for the lowest possible latency."),
  q("fs-08", "systems", "A cached account view remains stale after updates from several services. What is the right invalidation strategy?", "Define ownership and invalidate or version the cache from authoritative change events.", "Set every cache entry to expire after the same long fixed duration.", "Ask users to hard refresh whenever they expect updated information.", "Disable database transactions so cache and storage update independently."),
  q("fs-09", "systems", "A read model updates asynchronously and users briefly see old state. How should eventual consistency be handled?", "Make the state explicit, design monotonic transitions, and provide safe reconciliation behavior.", "Pretend writes are immediately consistent and hide all processing indicators.", "Retry every read until it exactly matches the command response.", "Write directly into every read replica from the browser."),
  q("fs-10", "systems", "An intermittent production failure crosses API, queue, and worker boundaries. What observability is most useful?", "Correlated traces, structured events, service metrics, and stable request or job identifiers.", "A single text log file on each developer machine.", "Only frontend error screenshots submitted by affected users.", "Debug logging of every secret and full request payload."),
  q("fs-11", "judgment", "A developer proposes placing a service credential in frontend code to simplify calls. What is the correct decision?", "Keep the credential server-side and expose a narrow authorized endpoint.", "Obfuscate the credential in the bundle so ordinary users cannot read it.", "Store it in local storage after the first authenticated request.", "Use a short variable name so automated scanners are less likely to find it."),
  q("fs-12", "judgment", "A public endpoint is being abused by automated high-volume requests. What rate-limit design is strongest?", "Use layered identity and IP limits, bounded cost, clear responses, and abuse monitoring.", "Block the first IP that exceeds an arbitrary total and never expire the block.", "Add a client-side delay because automated clients will respect it.", "Return successful placeholder responses to every request to hide overload."),
  q("fs-13", "judgment", "A managed provider and a custom subsystem both satisfy current requirements. How should build versus buy be decided?", "Compare strategic differentiation, total operating cost, constraints, exit path, and delivery risk.", "Always build because third-party dependencies reduce engineering ownership.", "Always buy because managed services never require operational work.", "Choose the option with the shortest marketing page and lowest starting price."),
  q("fs-14", "judgment", "Several failure modes are known but the team cannot address all before launch. What should be prioritized?", "Rank by likelihood, impact, detectability, and recovery, then mitigate the highest exposure.", "Fix the easiest issues first so the closed-ticket count rises quickly.", "Ignore failures that did not occur during the latest demonstration.", "Split time equally across every risk regardless of impact."),
  q("fs-15", "delivery", "A shared API change touches validation, persistence, and asynchronous processing. What test strategy is appropriate?", "Combine focused unit tests, contract tests, integration tests, and a critical-path end-to-end case.", "Use only end-to-end tests because they exercise the complete stack.", "Use only mocked unit tests because they are fastest to run.", "Test the happy path manually after deployment and monitor errors."),
  q("fs-16", "delivery", "An incident is causing data writes to fail for some customers. What should the responder do first?", "Contain impact, establish facts and ownership, communicate, and preserve evidence for recovery.", "Deploy several speculative fixes at once to maximize the chance of success.", "Delete failed records so monitoring returns to normal.", "Wait for the original feature author before taking any action."),
  q("fs-17", "delivery", "Consumers need time to migrate from an API response field. What communication and rollout is strongest?", "Version or add compatibly, publish a migration window, measure usage, and remove after confirmation.", "Rename the field immediately and let consumers discover the change through errors.", "Keep both fields forever without documenting which one is authoritative.", "Send one informal message and remove the field at the end of the day."),
  q("fs-18", "delivery", "A product scope has core workflow risk and many optional integrations. How should the first release be sequenced?", "Deliver the core vertical path and highest-risk integration early, then add optional breadth.", "Build every integration shell before the core workflow is usable.", "Complete the visual polish first and defer persistence until launch week.", "Choose tasks by developer preference without a shared dependency plan.")
]);
