import { question as q } from "../assessmentSchema.js";

export const productStrategyLeadQuestions = Object.freeze([
  q("ps-01", "craft", "A client presents a feature list but cannot state the business or user change they need. What should happen first?", "Frame the opportunity, target users, constraints, evidence, and measurable desired outcome.", "Estimate the feature list immediately so the client can secure budget.", "Choose the most innovative feature and make it the engagement theme.", "Ask design to visualize every feature before challenging the premise."),
  q("ps-02", "craft", "A four-week discovery must reduce uncertainty before a major build. What is the strongest plan?", "Prioritize critical assumptions, gather mixed evidence, prototype risks, and end with decisions.", "Interview as many people as possible without defining decision questions.", "Spend the full period documenting existing stakeholder opinions.", "Produce a detailed delivery roadmap before testing any assumption."),
  q("ps-03", "craft", "A roadmap has become a long dated list of requested features. How should it be restructured?", "Organize around outcomes and problems, show bets and dependencies, and update from evidence.", "Add more precise dates to every feature so the roadmap feels accountable.", "Remove uncertainty by labeling every request as committed.", "Sort items by the seniority of the stakeholder who requested them."),
  q("ps-04", "craft", "Several initiatives compete for one team and all sponsors call their work urgent. What is the best prioritization method?", "Use explicit outcome, evidence, reach, risk, cost, and dependency criteria with decision ownership.", "Divide the team's capacity equally among every sponsor.", "Start the initiative with the most polished presentation.", "Choose whichever request arrived first and avoid revisiting it."),
  q("ps-05", "craft", "A product goal is to improve onboarding but the team tracks only release output. What metric structure is strongest?", "Define a user outcome metric plus quality, time, and harm guardrails.", "Count the number of onboarding screens delivered each sprint.", "Use total application sessions because more traffic indicates success.", "Ask the team to report whether the new onboarding feels better."),
  q("ps-06", "craft", "A cross-functional workshop must resolve a product direction rather than just generate ideas. How should it be designed?", "Set the decision, evidence, roles, divergent and convergent steps, and named follow-through.", "Fill the agenda with open brainstorming and decide later in a separate meeting.", "Invite every possible observer and avoid assigning a decision owner.", "Begin with the leader's preferred solution so discussion remains efficient."),
  q("ps-07", "systems", "A launch depends on legal approval, data migration, provider setup, and training. How should dependencies be managed?", "Map owners, lead times, acceptance conditions, critical path, and escalation triggers.", "List dependencies in meeting notes and assume owners will remember them.", "Keep the product roadmap separate from operational dependencies.", "Schedule every dependency for the final week so teams stay focused."),
  q("ps-08", "systems", "A delivery plan has several uncertain integrations and a fixed external date. What is the best risk approach?", "Expose risks early, test high-uncertainty paths, hold contingencies, and review triggers frequently.", "Keep risks out of stakeholder updates until they become confirmed issues.", "Add more features so the launch still looks substantial if one integration fails.", "Use optimistic estimates to create urgency across the team."),
  q("ps-09", "systems", "Demand exceeds available specialist capacity across concurrent projects. What should resource planning do?", "Make constraints visible, limit work in progress, sequence by value and dependency, and protect critical roles.", "Assign each specialist to every project so all work can claim progress.", "Ask teams to absorb the gap through overtime without changing scope.", "Start new projects normally and resolve contention when deadlines arrive."),
  q("ps-10", "systems", "A fast-moving engagement keeps shipping defects and reopening completed work. What quality gates are appropriate?", "Define acceptance, automated and manual checks, review ownership, and release readiness by risk.", "Add one final approval meeting after all implementation is complete.", "Increase the number of status reports without changing acceptance criteria.", "Allow each discipline to decide independently when shared work is done."),
  q("ps-11", "judgment", "Two executive stakeholders demand incompatible priorities for the same team. What should the lead do?", "Clarify outcomes and constraints, present tradeoffs and evidence, then route the decision to the accountable owner.", "Promise both priorities and ask the team to discover a way to deliver them.", "Choose the stakeholder with the larger title without discussing tradeoffs.", "Delay all work until the stakeholders independently reach agreement."),
  q("ps-12", "judgment", "A client requests major scope after delivery begins but wants the same date and budget. What is the strongest response?", "Assess impact, offer explicit scope-time-cost options, and record the agreed change.", "Accept the request to preserve the relationship and ask the team to move faster.", "Reject all scope changes because plans should never evolve after kickoff.", "Add the work informally and remove quality checks to recover the schedule."),
  q("ps-13", "judgment", "A client asks the contractor team to direct employees outside the agreed engagement. How should the boundary be handled?", "Clarify authority and responsibilities, align the sponsor, and update the contract if needed.", "Act as their manager immediately because delivery outcomes are shared.", "Avoid all collaboration with employees to preserve contractor status.", "Continue quietly and leave accountability ambiguous."),
  q("ps-14", "judgment", "A critical risk is repeatedly ignored and could cause material customer harm. When should it be escalated?", "When the accountable level can change the outcome, with evidence, impact, options, and urgency.", "Only after harm occurs so the escalation is based on confirmed facts.", "Immediately to every executive before discussing it with the responsible owner.", "Never, because senior delivery leads should resolve every risk alone."),
  q("ps-15", "delivery", "A client update must communicate progress while one milestone is at risk. What should it include?", "Outcome progress, evidence, risk and impact, decisions needed, owners, and the next checkpoint.", "Only completed tasks so the client remains confident in the engagement.", "A raw export of every issue and internal conversation from the week.", "A general statement that the team is working hard to recover."),
  q("ps-16", "delivery", "A remote multidisciplinary team is losing decisions between meetings. What operating cadence is strongest?", "Use lightweight written decisions, clear owners, focused ceremonies, async updates, and review rhythms.", "Add a daily meeting for every specialist and require attendance throughout.", "Move all decisions into private chats so they can happen quickly.", "Avoid recurring cadence because autonomous teams should self-coordinate."),
  q("ps-17", "delivery", "A feature is technically complete but support, analytics, rollback, and operations are not ready. Is it launch-ready?", "No; readiness includes customer support, measurement, operations, recovery, and accountable sign-off.", "Yes; technical completion is the only objective launch criterion.", "Yes, if marketing has already announced the date publicly.", "No, and the feature should be abandoned rather than completing readiness work."),
  q("ps-18", "delivery", "A release shipped and initial metrics are mixed. What should the post-launch review produce?", "Compare outcomes and guardrails, examine evidence and incidents, decide actions, and assign owners.", "A celebration of completed scope without revisiting assumptions.", "A list of individual mistakes ranked by who caused them.", "A decision to wait indefinitely because mixed data cannot guide action." )
]);
