import { question as q } from "../assessmentSchema.js";

export const productDesignerQuestions = Object.freeze([
  q("pd-01", "craft", "A stakeholder asks for a dashboard before the underlying user problem is clear. What should the designer do first?", "Frame the user, decision, context, and desired outcome before choosing the interface form.", "Begin with a polished dashboard because stakeholders already named the solution.", "Collect visual references and let the strongest aesthetic determine the product structure.", "Ask engineering which chart library is easiest to implement."),
  q("pd-02", "craft", "Users cannot predict where account settings live across a complex product. What is the best information-architecture response?", "Model user concepts and tasks, test labels and grouping, then establish a consistent hierarchy.", "Add settings links to every screen so users eventually find the right one.", "Rename all navigation items with short abstract brand language.", "Place the most recently requested setting at the top each week."),
  q("pd-03", "craft", "A multi-step onboarding flow has high abandonment and repeated backtracking. What should be examined first?", "Map goals, dependencies, decisions, and error recovery across the complete task flow.", "Increase the progress indicator size so users notice how many steps remain.", "Remove the back action so users cannot disrupt the intended sequence.", "Add animation between steps to make the flow feel faster."),
  q("pd-04", "craft", "A custom interaction communicates state only through color and drag gestures. What is the strongest redesign?", "Add semantic state, text or shape cues, keyboard operation, focus, and equivalent controls.", "Choose more saturated colors and keep drag as the only input method.", "Add a tooltip that appears only when a mouse hovers over the control.", "Document the gesture in a separate help page and leave the control unchanged."),
  q("pd-05", "craft", "A long application form produces frequent errors near submission. What design change is most effective?", "Use persistent labels, logical grouping, clear constraints, inline errors, and preserved values.", "Replace labels with placeholders to reduce the visual density of the form.", "Validate only after submission and show one generic failure message.", "Clear invalid fields so users know exactly which values were rejected."),
  q("pd-06", "craft", "A team must decide whether a complex workflow is understandable before engineering begins. What prototype fidelity is appropriate?", "Use the lowest fidelity that accurately represents the risky interactions and content.", "Build a production-quality coded prototype for every screen before testing.", "Use static mood boards even though sequence and state are the main risks.", "Avoid prototyping and rely on stakeholder review of written requirements."),
  q("pd-07", "systems", "A usability study must compare two navigation structures. Which plan yields useful evidence?", "Recruit representative participants, define tasks and signals, use a consistent script, and synthesize patterns.", "Invite internal teammates who already know the product and ask which version they prefer.", "Show participants the design rationale before tasks so they understand the intended answer.", "Count only positive comments because hesitation is difficult to quantify."),
  q("pd-08", "systems", "A desktop workspace becomes a narrow mobile view with the same content priority. What should responsive hierarchy do?", "Reorder around the mobile task, preserve essential context, and progressively disclose secondary controls.", "Shrink the desktop canvas proportionally until every element fits the phone width.", "Hide all controls except the logo and ask users to switch devices.", "Keep the desktop order and add horizontal scrolling for every panel."),
  q("pd-09", "systems", "A new workflow resembles existing system patterns but has one meaningful difference. How should reuse be handled?", "Reuse stable primitives and extend the pattern only where the user need genuinely differs.", "Create an entirely new visual language so the workflow feels distinctive.", "Force the workflow into the old pattern even when the difference affects comprehension.", "Duplicate the existing components and edit local copies without system review."),
  q("pd-10", "systems", "A design covers the happy path but engineering finds many empty, loading, permission, and failure states. What should happen?", "Model the state matrix and design recovery, permissions, latency, and empty states before handoff.", "Ask engineering to invent those states while implementing the happy path.", "Use one generic modal for every state so no new layouts are needed.", "Remove state transitions from the prototype to keep review focused."),
  q("pd-11", "judgment", "Research evidence conflicts with a senior stakeholder's preferred solution. What is the strongest response?", "Present the evidence and uncertainty, connect it to outcomes, and propose a focused test or decision.", "Ignore the evidence because the stakeholder is accountable for the final result.", "Refuse to continue until the stakeholder accepts every research conclusion.", "Change the research summary so it appears to support the preferred solution."),
  q("pd-12", "judgment", "A team wants one metric to judge whether a new workflow succeeds. Which metric is best?", "Choose a behavior tied to the user outcome, with guardrails for quality and unintended effects.", "Use page views because they are available for every feature.", "Use total clicks because more interaction always indicates greater value.", "Use stakeholder satisfaction instead of observing user behavior."),
  q("pd-13", "judgment", "Several usability issues compete with a high-visibility visual refresh. How should priorities be set?", "Compare user impact, frequency, strategic value, risk, and effort with the team.", "Always choose the visual refresh because leadership will notice it first.", "Fix issues strictly in the order they were reported.", "Split design time evenly without considering severity or reach."),
  q("pd-14", "judgment", "During critique, feedback requests a solution that conflicts with the stated user goal. What should the designer do?", "Clarify the underlying concern, restate the goal and constraints, then evaluate alternatives.", "Apply the requested solution immediately to show responsiveness.", "Reject the feedback because only the designer understands the user experience.", "Collect votes from the room and choose the most popular visual option."),
  q("pd-15", "delivery", "Engineering is beginning a state-heavy workflow. What handoff is most useful?", "Provide intent, flows, states, content, responsive rules, tokens, and direct implementation discussion.", "Send only final screenshots so engineering has freedom to infer behavior.", "Provide a long animation video without state annotations or reusable values.", "Wait until implementation is complete before answering interaction questions."),
  q("pd-16", "delivery", "Research produced interviews, observations, and conflicting notes across participants. How should synthesis work?", "Code evidence, identify patterns and exceptions, trace insights to sources, and state confidence.", "Select the most memorable quotes and treat them as the dominant pattern.", "Average every comment into one generalized user persona.", "Remove contradictory evidence so the final presentation is decisive."),
  q("pd-17", "delivery", "A redesigned flow launches with uncertain behavior change. What validation plan is strongest?", "Measure agreed outcome and guardrails, observe real use, review support signals, and iterate.", "Declare success when the release ships without visual defects.", "Wait six months before looking at any behavior so data is fully stable.", "Use only the design team's qualitative opinion after launch."),
  q("pd-18", "delivery", "A deadline cannot support every proposed flow and edge case. How should scope be negotiated?", "Protect the core outcome and critical recovery states, expose tradeoffs, and sequence the rest.", "Remove accessibility work because it is less visible in stakeholder demos.", "Keep every screen but reduce design review and engineering QA.", "Let each discipline independently remove whichever work seems hardest." )
]);
